#!/bin/sh
dmd -debug -gs -gf -g -gx -ofmain `ls ./src/*.d` `ls ./toml/src/toml/*.d` -L-L./lib/ 

# -gx produce "stack stomp code"
# LDC equivalent? https://github.com/ldc-developers/ldc/issues/2489


# -gdwarf=5
# -preview=shortenedMethods  should be automatically on by newer versions as of early 2023


# we didn't need $@ https://stackoverflow.com/questions/3898665/what-is-in-bash
#-vgc 
#-release
# -gc optmize for non-D debuggers
# -O3 max debug (may allow others later)
#  -march=<string>                   - Architecture to generate code for:
#  -mattr=<a1,+a2,-a3,...>           - Target specific attributes (-mattr=help for details)
#  -mcpu=<cpu-name>                  - Target a specific cpu type (-mcpu=help for details)
