#!/bin/sh

#of  output file
#ldc2 -w -release -ofmain main.d -L-L. $@    -gc -d-debug=3  -de

#ldc2 -w -release -ofmain main.d helper.d -L-L/usr/local/lib/ -L-L. $@
#ldc2 -w -d-debug -ofmain main.d helper.d objects.d viewport.d g.d gui.d -L-L/usr/local/lib/ -L-L. $@
ldc2 -wi -d-debug -g --gc -stats -ofmain `ls ./src/*.d` -L-L/usr/local/lib/ -L-L./lib/ $@ --preview=shortenedMethods


#  --checkaction=context
# doesn't work atm, missing stdlib assert function it's looking for?
#  /home/novous/Desktop/git/dlawn/./src/g.d:137: undefined reference to `_D4core8internal7dassert__T14_d_assert_failTbZQtFNaNbNiNfMxAyaxbZAya'
# /usr/bin/ld: main.o: in function `_D1g13bitmapHandler3getMFAyaZPS8allegro56bitmap14ALLEGRO_BITMAP':



#  -fprofile-instr-generate
# https://wiki.dlang.org/LDC_LLVM_profiling_instrumentation


# globals.d 

#-release
# -gc optmize for non-D debuggers
# -O3 max debug (may allow others later)

#  -march=<string>                   - Architecture to generate code for:
#  -mattr=<a1,+a2,-a3,...>           - Target specific attributes (-mattr=help for details)
#  -mcpu=<cpu-name>                  - Target a specific cpu type (-mcpu=help for details)


# TRY THESE
#
# ldc2 -mattr=help
# ldc2 -mcpu=help 


# Talk on supported versions:
# http://llvm.org/devmtg/2014-04/PDFs/LightningTalks/2014-3-31_ClangTargetSupport_LighteningTalk.pdf


# -de  show use of deprecated features as errors (halt compilation) 
#https://wiki.dlang.org/Using_LDC
