#!/bin/sh
#dmd -profile -profile=gc -debug -gs -g -ofmain main.d helper.d objects.d viewport.d g.d -L-L. $@
dmd -profile -profile=gc -debug -gs -g -ofprofmain `ls ./src/*.d` `ls ./toml/src/toml/*.d` -L-L./lib/ $@
echo " * deleting old trace log files because they're cumulative."
rm trace.log >> /dev/null 2>&1 
rm trace.def >> /dev/null 2>&1
rm profilegc.log >> /dev/null 2>&1
